import {
  GATEWAY_EVENT_DEVICE_PAIR_CHANGED,
  GATEWAY_EVENT_NODE_RUNNER_INVENTORY_CHANGED,
  GATEWAY_EVENT_UPDATE_RUN_CHANGED,
} from "./events.js";
import {
  ADMIN_SCOPE,
  APPROVALS_SCOPE,
  PAIRING_SCOPE,
  QUESTIONS_SCOPE,
  READ_SCOPE,
  SESSION_READ_SCOPE,
  TALK_SCOPE,
} from "./operator-scopes.js";

// Pairing scope is for device-pairing handshakes only; chat transcript events
// require operator-level session access. Pairing-scoped and node-role clients
// must not passively receive chat-class broadcasts.
export const EVENT_SCOPE_GUARDS: Record<string, string[]> = {
  agent: [SESSION_READ_SCOPE],
  chat: [SESSION_READ_SCOPE],
  "chat.metadata.changed": [SESSION_READ_SCOPE],
  "board.changed": [READ_SCOPE],
  "board.command": [READ_SCOPE],
  "progressCard.changed": [SESSION_READ_SCOPE],
  "ui.command": [READ_SCOPE],
  "chat.send_timing": [READ_SCOPE],
  "chat.side_result": [SESSION_READ_SCOPE],
  cron: [READ_SCOPE],
  health: [],
  "exec.approval.requested": [APPROVALS_SCOPE],
  "exec.approval.resolved": [APPROVALS_SCOPE],
  "question.requested": [QUESTIONS_SCOPE],
  "question.resolved": [QUESTIONS_SCOPE],
  heartbeat: [],
  "plugin.approval.requested": [APPROVALS_SCOPE],
  "plugin.approval.resolved": [APPROVALS_SCOPE],
  "openclaw.approval.requested": [APPROVALS_SCOPE],
  "openclaw.approval.resolved": [APPROVALS_SCOPE],
  // The frame cadence itself exposes person activity; match system-presence access.
  presence: [READ_SCOPE],
  shutdown: [],
  "gateway.suspension": [],
  tick: [],
  "talk.event": [READ_SCOPE],
  "talk.mode": [TALK_SCOPE],
  "talk.voice.change": [TALK_SCOPE],
  task: [READ_SCOPE],
  "task.suggestion": [READ_SCOPE],
  "update.available": [],
  [GATEWAY_EVENT_UPDATE_RUN_CHANGED]: [ADMIN_SCOPE],
  // Hash-only change notice after a persisted config write; content stays
  // behind the operator-scoped config.get.
  "config.changed": [READ_SCOPE],
  "users.prefs.changed": [SESSION_READ_SCOPE],
  "mentions.changed": [READ_SCOPE],
  "skills.changed": [READ_SCOPE],
  "plugins.changed": [READ_SCOPE],
  "plugins.install.progress": [ADMIN_SCOPE],
  "voicewake.changed": [READ_SCOPE],
  "voicewake.routing.changed": [READ_SCOPE],
  [GATEWAY_EVENT_DEVICE_PAIR_CHANGED]: [PAIRING_SCOPE],
  "device.pair.requested": [PAIRING_SCOPE],
  "device.pair.resolved": [PAIRING_SCOPE],
  "device.pair.setup.completed": [PAIRING_SCOPE],
  "device.pair.setup.deliveryUncertain": [PAIRING_SCOPE],
  "node.pair.requested": [PAIRING_SCOPE],
  "node.pair.resolved": [PAIRING_SCOPE],
  "node.presence": [READ_SCOPE],
  "node.hostStats": [READ_SCOPE],
  [GATEWAY_EVENT_NODE_RUNNER_INVENTORY_CHANGED]: [READ_SCOPE],
  "sessions.catalog.host": [READ_SCOPE],
  "sessions.changed": [SESSION_READ_SCOPE],
  "controlUi.sessionPullRequests.changed": [READ_SCOPE],
  "plugins.controlUi.changed": [READ_SCOPE],
  "session.approval": [APPROVALS_SCOPE],
  "session.message": [SESSION_READ_SCOPE],
  "session.observer": [SESSION_READ_SCOPE],
  "session.operation": [READ_SCOPE],
  "session.sharing": [READ_SCOPE],
  "session.sharing.evidence": [READ_SCOPE],
  "session.suggestion": [SESSION_READ_SCOPE],
  "session.typing": [SESSION_READ_SCOPE],
  "session.tool": [SESSION_READ_SCOPE],
  // Operator terminal byte/exit streams. Admin-gated to match the terminal.*
  // methods; also targeted to the owning connection at broadcast time.
  "terminal.data": [ADMIN_SCOPE],
  "terminal.exit": [ADMIN_SCOPE],
  "portal.changed": [READ_SCOPE],
};
