// Curated emoji options for the agent identity emoji picker dropdown.
// Grouped for readability in the native <select>; values are the raw glyphs
// stored as the agent's identity emoji (same field the free-text input sets).

export type EmojiCatalogGroup = {
  label: string;
  options: Array<{ emoji: string; label: string }>;
};

export const EMOJI_CATALOG: EmojiCatalogGroup[] = [
  {
    label: "Mammals",
    options: [
      { emoji: "🐶", label: "Dog" },
      { emoji: "🐱", label: "Cat" },
      { emoji: "🦊", label: "Fox" },
      { emoji: "🐺", label: "Wolf" },
      { emoji: "🐻", label: "Bear" },
      { emoji: "🐼", label: "Panda" },
      { emoji: "🐨", label: "Koala" },
      { emoji: "🦁", label: "Lion" },
      { emoji: "🐯", label: "Tiger" },
      { emoji: "🐮", label: "Cow" },
      { emoji: "🐷", label: "Pig" },
      { emoji: "🐭", label: "Mouse" },
      { emoji: "🐹", label: "Hamster" },
      { emoji: "🐰", label: "Rabbit" },
      { emoji: "🦝", label: "Raccoon" },
      { emoji: "🦇", label: "Bat" },
      { emoji: "🐴", label: "Horse" },
      { emoji: "🦓", label: "Zebra" },
      { emoji: "🦌", label: "Deer" },
      { emoji: "🐘", label: "Elephant" },
    ],
  },
  {
    label: "Birds & Sea",
    options: [
      { emoji: "🦞", label: "Lobster" },
      { emoji: "🐧", label: "Penguin" },
      { emoji: "🦉", label: "Owl" },
      { emoji: "🐙", label: "Octopus" },
      { emoji: "🐢", label: "Turtle" },
      { emoji: "🐬", label: "Dolphin" },
      { emoji: "🦈", label: "Shark" },
      { emoji: "🦅", label: "Eagle" },
      { emoji: "🦆", label: "Duck" },
      { emoji: "🦢", label: "Swan" },
      { emoji: "🦜", label: "Parrot" },
      { emoji: "🐦", label: "Bird" },
      { emoji: "🦩", label: "Flamingo" },
      { emoji: "🐳", label: "Whale" },
      { emoji: "🐋", label: "Blue Whale" },
      { emoji: "🦑", label: "Squid" },
      { emoji: "🦀", label: "Crab" },
      { emoji: "🐠", label: "Fish" },
      { emoji: "🐡", label: "Pufferfish" },
    ],
  },
  {
    label: "Bugs & Reptiles",
    options: [
      { emoji: "🦋", label: "Butterfly" },
      { emoji: "🐝", label: "Bee" },
      { emoji: "🦔", label: "Hedgehog" },
      { emoji: "🐌", label: "Snail" },
      { emoji: "🐛", label: "Caterpillar" },
      { emoji: "🐞", label: "Ladybug" },
      { emoji: "🕷️", label: "Spider" },
      { emoji: "🦂", label: "Scorpion" },
      { emoji: "🐜", label: "Ant" },
      { emoji: "🦗", label: "Cricket" },
      { emoji: "🐍", label: "Snake" },
      { emoji: "🦎", label: "Lizard" },
      { emoji: "🐊", label: "Crocodile" },
      { emoji: "🦕", label: "Sauropod" },
      { emoji: "🦖", label: "T-Rex" },
      { emoji: "🐸", label: "Frog" },
    ],
  },
  {
    label: "Faces & People",
    options: [
      { emoji: "🙂", label: "Smile" },
      { emoji: "😎", label: "Sunglasses" },
      { emoji: "😀", label: "Grinning Face" },
      { emoji: "😄", label: "Laughing Face" },
      { emoji: "😁", label: "Beaming Face" },
      { emoji: "😊", label: "Blushing Face" },
      { emoji: "😇", label: "Halo Face" },
      { emoji: "🤓", label: "Nerd Face" },
      { emoji: "🧐", label: "Monocle Face" },
      { emoji: "🙃", label: "Upside-Down Face" },
      { emoji: "😉", label: "Winking Face" },
      { emoji: "🥳", label: "Party Face" },
      { emoji: "🤠", label: "Cowboy Face" },
      { emoji: "🥸", label: "Disguise Face" },
      { emoji: "🕵️", label: "Detective" },
      { emoji: "🤡", label: "Clown" },
    ],
  },
  {
    label: "Fantasy & Robots",
    options: [
      { emoji: "🤖", label: "Robot" },
      { emoji: "👾", label: "Alien Monster" },
      { emoji: "👻", label: "Ghost" },
      { emoji: "🧙", label: "Wizard" },
      { emoji: "🥷", label: "Ninja" },
      { emoji: "🧠", label: "Brain" },
      { emoji: "🐉", label: "Dragon" },
      { emoji: "🦄", label: "Unicorn" },
      { emoji: "🧛", label: "Vampire" },
      { emoji: "🧟", label: "Zombie" },
      { emoji: "👽", label: "Alien" },
      { emoji: "🎅", label: "Santa" },
      { emoji: "🧞", label: "Genie" },
      { emoji: "🧚", label: "Fairy" },
      { emoji: "🧜", label: "Merperson" },
      { emoji: "💀", label: "Skull" },
      { emoji: "☠️", label: "Skull and Crossbones" },
      { emoji: "👹", label: "Ogre" },
      { emoji: "👺", label: "Goblin" },
    ],
  },
  {
    label: "Nature & Weather",
    options: [
      { emoji: "🌙", label: "Moon" },
      { emoji: "☀️", label: "Sun" },
      { emoji: "🌈", label: "Rainbow" },
      { emoji: "⭐", label: "Star" },
      { emoji: "✨", label: "Sparkles" },
      { emoji: "⚡", label: "Lightning" },
      { emoji: "🔥", label: "Fire" },
      { emoji: "❄️", label: "Snowflake" },
      { emoji: "☃️", label: "Snowman" },
      { emoji: "🌊", label: "Wave" },
      { emoji: "🌪️", label: "Tornado" },
      { emoji: "🌋", label: "Volcano" },
      { emoji: "🌸", label: "Cherry Blossom" },
      { emoji: "🌺", label: "Hibiscus" },
      { emoji: "🌻", label: "Sunflower" },
      { emoji: "🌵", label: "Cactus" },
      { emoji: "🍀", label: "Clover" },
      { emoji: "🌴", label: "Palm Tree" },
      { emoji: "🌳", label: "Tree" },
      { emoji: "🌟", label: "Glowing Star" },
    ],
  },
  {
    label: "Food & Drink",
    options: [
      { emoji: "🍕", label: "Pizza" },
      { emoji: "🍔", label: "Burger" },
      { emoji: "🍟", label: "Fries" },
      { emoji: "🌮", label: "Taco" },
      { emoji: "🍣", label: "Sushi" },
      { emoji: "🍩", label: "Donut" },
      { emoji: "🍪", label: "Cookie" },
      { emoji: "🍰", label: "Cake" },
      { emoji: "🎂", label: "Birthday Cake" },
      { emoji: "🍎", label: "Apple" },
      { emoji: "🍌", label: "Banana" },
      { emoji: "🍇", label: "Grapes" },
      { emoji: "🍉", label: "Watermelon" },
      { emoji: "🍓", label: "Strawberry" },
      { emoji: "🥑", label: "Avocado" },
      { emoji: "🍿", label: "Popcorn" },
      { emoji: "☕", label: "Coffee" },
      { emoji: "🍺", label: "Beer" },
      { emoji: "🍷", label: "Wine" },
      { emoji: "🥐", label: "Croissant" },
    ],
  },
  {
    label: "Objects & Tools",
    options: [
      { emoji: "💎", label: "Gem" },
      { emoji: "🎯", label: "Target" },
      { emoji: "🧭", label: "Compass" },
      { emoji: "⚙️", label: "Gear" },
      { emoji: "🔧", label: "Wrench" },
      { emoji: "🗝️", label: "Key" },
      { emoji: "🛡️", label: "Shield" },
      { emoji: "🏆", label: "Trophy" },
      { emoji: "🔨", label: "Hammer" },
      { emoji: "🔍", label: "Magnifying Glass" },
      { emoji: "📌", label: "Pushpin" },
      { emoji: "📎", label: "Paperclip" },
      { emoji: "🔒", label: "Locked" },
      { emoji: "🔓", label: "Unlocked" },
      { emoji: "💡", label: "Light Bulb" },
      { emoji: "🔋", label: "Battery" },
      { emoji: "🕯️", label: "Candle" },
      { emoji: "⚖️", label: "Scales" },
      { emoji: "⛏️", label: "Pick" },
      { emoji: "🧲", label: "Magnet" },
    ],
  },
  {
    label: "Tech & Science",
    options: [
      { emoji: "🚀", label: "Rocket" },
      { emoji: "📡", label: "Antenna" },
      { emoji: "🛰️", label: "Satellite" },
      { emoji: "💻", label: "Laptop" },
      { emoji: "🖥️", label: "Desktop Computer" },
      { emoji: "⌨️", label: "Keyboard" },
      { emoji: "🖱️", label: "Computer Mouse" },
      { emoji: "📱", label: "Mobile Phone" },
      { emoji: "☎️", label: "Telephone" },
      { emoji: "🔬", label: "Microscope" },
      { emoji: "🔭", label: "Telescope" },
      { emoji: "🧪", label: "Test Tube" },
      { emoji: "🧬", label: "DNA" },
      { emoji: "⚛️", label: "Atom" },
      { emoji: "🛸", label: "Flying Saucer" },
      { emoji: "💾", label: "Floppy Disk" },
      { emoji: "🧮", label: "Abacus" },
    ],
  },
  {
    label: "Travel & Places",
    options: [
      { emoji: "🌍", label: "Globe Europe-Africa" },
      { emoji: "🌎", label: "Globe Americas" },
      { emoji: "🌏", label: "Globe Asia-Australia" },
      { emoji: "🗺️", label: "World Map" },
      { emoji: "🏔️", label: "Mountain" },
      { emoji: "🏝️", label: "Desert Island" },
      { emoji: "🏰", label: "Castle" },
      { emoji: "🗼", label: "Tower" },
      { emoji: "🎡", label: "Ferris Wheel" },
      { emoji: "⛺", label: "Tent" },
      { emoji: "🚂", label: "Train" },
      { emoji: "✈️", label: "Airplane" },
      { emoji: "🚁", label: "Helicopter" },
      { emoji: "🚢", label: "Ship" },
      { emoji: "🚗", label: "Car" },
      { emoji: "🛵", label: "Scooter" },
      { emoji: "🚲", label: "Bicycle" },
      { emoji: "⛵", label: "Sailboat" },
    ],
  },
  {
    label: "Sports & Games",
    options: [
      { emoji: "⚽", label: "Soccer Ball" },
      { emoji: "🏀", label: "Basketball" },
      { emoji: "🏈", label: "Football" },
      { emoji: "⚾", label: "Baseball" },
      { emoji: "🎾", label: "Tennis" },
      { emoji: "🏐", label: "Volleyball" },
      { emoji: "🏓", label: "Ping Pong" },
      { emoji: "🎳", label: "Bowling" },
      { emoji: "🎮", label: "Video Game" },
      { emoji: "🎲", label: "Dice" },
      { emoji: "🃏", label: "Joker" },
      { emoji: "🎱", label: "8 Ball" },
      { emoji: "🥊", label: "Boxing Glove" },
      { emoji: "🏹", label: "Bow and Arrow" },
      { emoji: "🎣", label: "Fishing Pole" },
      { emoji: "🛹", label: "Skateboard" },
    ],
  },
  {
    label: "Hearts & Shapes",
    options: [
      { emoji: "❤️", label: "Red Heart" },
      { emoji: "🧡", label: "Orange Heart" },
      { emoji: "💛", label: "Yellow Heart" },
      { emoji: "💚", label: "Green Heart" },
      { emoji: "💙", label: "Blue Heart" },
      { emoji: "💜", label: "Purple Heart" },
      { emoji: "🖤", label: "Black Heart" },
      { emoji: "🤍", label: "White Heart" },
      { emoji: "🤎", label: "Brown Heart" },
      { emoji: "💖", label: "Sparkling Heart" },
      { emoji: "💗", label: "Growing Heart" },
      { emoji: "💫", label: "Dizzy Star" },
      { emoji: "♻️", label: "Recycling" },
      { emoji: "☮️", label: "Peace Symbol" },
      { emoji: "☯️", label: "Yin Yang" },
      { emoji: "♠️", label: "Spade Suit" },
      { emoji: "♣️", label: "Club Suit" },
      { emoji: "♦️", label: "Diamond Suit" },
    ],
  },
];
